from copy import deepcopy

from ..fonts import get_font_config
from .theme_overrides import THEME_OVERRIDES


_BASE_THEME = {
    'colors': {
        'bg': '#F4F8F7',
        'bg_app': '#F4F8F7',
        'bg_shell': '#EDF4F2',
        'panel': '#FCFDFC',
        'panel_elevated': '#FFFFFF',
        'panel_tinted': '#F6FBF9',
        'card_bg': '#FCFDFC',
        'card_alt': '#F6FBF9',
        'input_bg': '#F8FCFB',
        'input_border': '#C9DDD8',
        'input_focus': '#7FAEA6',
        'border': '#D7E5E1',
        'border_strong': '#B8D1CB',
        'line_soft': '#D7E5E1',
        'line_strong': '#B8D1CB',
        'line_gold': '#D0B173',
        'accent': '#6FA59D',
        'accent_dark': '#4C7C76',
        'accent_deep': '#3A6661',
        'accent_soft': '#DCECE8',
        'gold': '#C9A86A',
        'gold_bright': '#DDBE83',
        'gold_deep': '#9D7A42',
        'gold_soft': '#F2E5C8',
        'pink_soft': '#F6E4E8',
        'text': '#27383D',
        'text_strong': '#1D2C30',
        'muted': '#657B7D',
        'subtext': '#89A0A2',
        'text_muted': '#657B7D',
        'text_soft': '#89A0A2',
        'hover': '#EEF6F3',
        'separator': '#DDE9E5',
        'tab_bg': '#E7F1EE',
        'tab_active': '#FFF4E7',
        'user': '#F8F3E8',
        'assistant': '#F3F8F6',
        'assistant_bubble': '#F3F8F6',
        'assistant_edge': '#C9DDD8',
        'user_bubble': '#F8F3E8',
        'user_edge': '#DDC798',
        'warn': '#FBF4E7',
        'warn_edge': '#E2C78F',
        'error': '#FAECEC',
        'danger_bg': '#FAECEC',
        'danger_edge': '#DEB7B7',
        'success': '#EDF7F1',
        'success_edge': '#BFD9C8',
        'info': '#E7F3F5',
        'white': '#FFFFFF',
    },
    'spacing': {
        'window_pad': 18,
        'section_gap': 14,
        'button_gap': 10,
        'card_pad_x': 12,
        'card_pad_y': 10,
    },
    'windows': {
        'chat': {
            'base_width': 940,
            'base_height': 760,
            'min_width': 620,
            'min_height': 480,
            'outer_pad': 20,
            'header_gap': 14,
            'composer_gap': 12,
            'button_gap': 12,
            'input_height': 5,
        },
        'settings': {
            'base_width': 1000,
            'base_height': 1000,
            'min_width': 600,
            'min_height': 600,
            'outer_pad_x': 24,
            'outer_pad_y': 20,
        },
        'menu': {
            'title_height': 24,
            'screen_margin': 12,
            'slide_offset_y': 8,
            'slide_steps': 5,
            'slide_interval_ms': 18,
        },
    },
    'chat': {
        'sidebar_width': 276,
        'history_wraplength': 208,
        'header_pad_x': 18,
        'header_pad_y': 16,
        'header_status_width': 140,
        'control_pad_x': 16,
        'control_pad_y': 14,
        'control_gap': 10,
        'transcript_header_pad_x': 16,
        'transcript_header_pad_y': 12,
        'transcript_pad_x': 18,
        'transcript_pad_y': 16,
        'transcript_status_width': 120,
        'bubble_pad_x': 14,
        'bubble_pad_y': 12,
        'bubble_gap_y': 8,
        'bubble_strip_height': 4,
        'bubble_max_width': 540,
        'user_bubble_max_width': 440,
        'input_shell_height': 128,
        'input_pad_x': 14,
        'input_pad_y': 12,
        'composer_pad_x': 16,
        'composer_pad_y': 14,
        'inline_card_pad_x': 14,
        'inline_card_pad_y': 12,
        'permission_wraplength': 520,
        'permission_summary_max_chars': 600,
    },
    'menu': {
        'title_text': 'Quick Menu',
        'subtitle_text': 'Control Center',
        'item_pad_x': 14,
        'item_pad_y': 10,
        'item_frame_pad_x': 10,
        'item_frame_pad_y': 4,
        'item_indicator_width': 5,
        'item_border_width': 1,
        'separator_pad_x': 18,
        'separator_pad_y': 8,
        'title_pad_x': 14,
        'title_pad_y': 12,
        'header_pad_x': 10,
        'header_pad_y': 10,
        'body_pad_x': 10,
        'body_pad_y': 10,
    },
    'settings': {
        'tab_padding': (14, 7),
        'tab_padding_selected': (18, 9),
    },
    'buttons': {
        'primary': {
            'bg': 'accent',
            'fg': 'white',
            'activebackground': 'accent_dark',
            'activeforeground': 'white',
            'highlightbackground': 'accent_dark',
            'highlightthickness': 1,
            'relief': 'flat',
            'bd': 0,
            'cursor': 'hand2',
            'compound': 'center',
            'hover_bg': 'accent_dark',
            'hover_fg': 'white',
            'hover_border_color': 'accent_deep',
            'hover_highlightthickness': 1,
            'pressed_bg': 'accent_deep',
            'pressed_fg': 'white',
            'pressed_border_color': 'accent_deep',
            'pressed_highlightthickness': 1,
            'pulse_border_off_color': 'accent',
            'pulse_step_ms': 0,
            'pulse_steps': 0,
            'image': None,
            'hover_image': None,
            'pressed_image': None,
            'image_size': None,
        },
        'secondary': {
            'bg': 'panel_elevated',
            'fg': 'text',
            'activebackground': 'hover',
            'activeforeground': 'text',
            'highlightbackground': 'line_strong',
            'highlightthickness': 1,
            'relief': 'flat',
            'bd': 0,
            'cursor': 'hand2',
            'compound': 'center',
            'hover_bg': 'panel_tinted',
            'hover_fg': 'text',
            'hover_border_color': 'line_gold',
            'pressed_bg': 'hover',
            'pressed_fg': 'text',
            'pressed_border_color': 'line_strong',
            'pulse_border_off_color': 'panel_elevated',
            'pulse_step_ms': 0,
            'pulse_steps': 0,
            'image': None,
            'hover_image': None,
            'pressed_image': None,
            'image_size': None,
        },
        'ghost': {
            'bg': 'panel_tinted',
            'fg': 'text',
            'activebackground': 'hover',
            'activeforeground': 'text',
            'highlightbackground': 'line_soft',
            'highlightthickness': 1,
            'relief': 'flat',
            'bd': 0,
            'cursor': 'hand2',
            'compound': 'center',
            'hover_bg': 'panel_elevated',
            'hover_fg': 'text',
            'hover_border_color': 'line_gold',
            'pressed_bg': 'hover',
            'pressed_fg': 'text',
            'pressed_border_color': 'line_strong',
            'pulse_border_off_color': 'panel_tinted',
            'pulse_step_ms': 0,
            'pulse_steps': 0,
            'image': None,
            'hover_image': None,
            'pressed_image': None,
            'image_size': None,
        },
    },
    'bubble': {
        'permission_bg': 'info',
        'permission_border': 'accent_soft',
        'celebrating_bg': 'success',
        'celebrating_border': 'accent',
        'building_bg': 'warn',
        'building_border': 'gold',
        'fetching_bg': 'info',
        'fetching_border': 'accent',
        'searching_bg': 'pink_soft',
        'searching_border': 'gold_soft',
        'analyzing_bg': 'warn',
        'analyzing_border': 'gold_soft',
    },
}


def _build_fonts(font_config):
    family = font_config['family']
    base_size = font_config['base'][1]
    small_size = font_config['small'][1]
    control_size = font_config['control'][1]
    return {
        'family': family,
        'hero': (family, max(base_size + 6, font_config['title'][1] + 2), 'bold'),
        'title': font_config['title'],
        'subtitle': font_config['subtitle'],
        'base': font_config['base'],
        'small': font_config['small'],
        'control': font_config['control'],
        'eyebrow': (family, small_size, 'bold'),
        'mono': ('Consolas', max(9, base_size - 1)),
        'menu_title': (family, max(base_size, small_size + 1), 'bold'),
        'menu_item': (family, base_size),
        'caption': (family, small_size),
        'button': (family, control_size),
    }


def _deep_merge(base, overrides):
    for key, value in overrides.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _deep_merge(base[key], value)
        else:
            base[key] = value
    return base


def get_theme():
    theme = deepcopy(_BASE_THEME)
    theme['fonts'] = _build_fonts(get_font_config())
    _deep_merge(theme, deepcopy(THEME_OVERRIDES))
    return theme
